# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7054edfa20f872093fe2e63df7a35735205113a400c6577b24452f33c5d3f58010948ab60af26d8cf3fb000bf8ba75caf16055994cc8c99c7b00777ce043ef1e

test:
  secret_key_base: 528022fcc5f3a512d0bfe8870c787d57983b792c45361853d649157c528c336a8fcbc27a799c08202bee4ebdce1d40e9248acc2926cf012caf000ae53b9e6b33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
